#%RAML 1.0
title: kafka-consumption-papi

types:
  seek: !include types/seek.raml

/orders:
  /seek:
    post:
      displayName: Set offset of one or more topic partitions
      body:
        application/json:
          type: seek
          example: !include examples/seek.json
      responses:
        202:
          body:
            application/json:
              examples:
                message: Seek request accepted.
  /start:
    post:
      displayName: Start listener for consumption
      responses:
        200:
          body:
            application/json:
              examples:
                message: Listener started.
        304:
          body:
            application/json:
              examples:
                message: Listener already running.